- src: git@gitlab.mobidev.biz:ansible/initial.git
  scm: git
  version: v1.0

- src: git@gitlab.mobidev.biz:ansible/composer.git
  scm: git
  version: v1.1

- src: git@gitlab.mobidev.biz:ansible/nginx.git
  scm: git
  version: v1.8

- src: git@gitlab.mobidev.biz:ansible/mariadb-10-1.git
  scm: git
  version: v1.0

- src: git@gitlab.mobidev.biz:ansible/php5-ubuntu.git
  scm: git
  version: v1.0

- src: git@gitlab.mobidev.biz:ansible/phpmyadmin.git
  scm: git
  version: v1.4

- src: git@gitlab.mobidev.biz:ansible/backup-mysql.git
  scm: git
  version: v1.0

- src: git@gitlab.mobidev.biz:ansible/prepare-deploy-pack.git
  scm: git

- src: git@gitlab.mobidev.biz:ansible/deploy.git
  scm: git