---
# handlers file for phpredis
- name: restart php-fpm
  service: name="php{{ php_version }}-fpm" state=restarted
  ignore_errors: yes

- name: restart apache
  service: name=apache2 state=restarted
  ignore_errors: yes