---
# handlers file for phpredis

- name: restart php5-fpm
  service: name=php5-fpm state=restarted
  ignore_errors: yes

- name: restart php7.0-fpm
  service: name=php7.0-fpm state=restarted
  ignore_errors: yes

- name: restart apache
  service: name=apache2 state=restarted
  ignore_errors: yes