---
# tasks file for supervisor

- name: install supervisor debian/ubuntu
  apt: pkg=supervisor state=latest

- name: ensure supervisor conf.d directory exists
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: ensure supervisor log directory exists
  file:
    path: /var/log/supervisor
    state: directory

- name: Copy supervisor global configuration
  template: src="{{ supervisord_default_conf_file }}" dest=/etc/supervisor/supervisord.conf