# vars for initial
hostname: advanced-master.local
env: Development
deploy_project_name: yii2-advanced-master

packages: [
  git-core,
  curl,
  wget,
  htop,
  python-psycopg2,
  libpq-dev,
  unzip,
  zip,
  expect-dev,
  mc
]

# vars for Nginx
nginx_php_unix_socket: /var/run/php5-fpm.sock

# hosts
nginx_vhosts: [
    { server_name: '_', root: '/var/www/yii2-advanced-master', template: 'catch_all'},
    { server_name: 'db.advanced-master.local', root: '/usr/share/phpmyadmin', template: 'php'},
    { server_name: 'advanced-master.local',  root: '/var/www/yii2-advanced-master/frontend/web', template: 'yii'},
    { server_name: 'api.advanced-master.local',  root: '/var/www/yii2-advanced-master/api/web', template: 'yii'},
    { server_name: 'admin.advanced-master.local',  root: '/var/www/yii2-advanced-master/backend/web', template: 'yii'},
]

# vars for php5-ubuntu
php5_file_uploads: On
php5_max_file_uploads: 25
php5_packages: [
    php5,
    php5-fpm,
    php5-dev,
    php5-cli,
    php5-pgsql,
    php5-mysql,
    php5-curl,
    php5-gd,
    php5-mcrypt
]

# vars for mariadb-10-1
mariadb:
    root_password: pass
    user: pet
    password: petpass
    databases: [
        ptt_pet
    ]

# vars for phpmyadmin
mysql_root_pass: "{{ mariadb.root_password }}"

deploy_run_user: www-data
deploy_run_group: www-data
deploy_folder_permissions: 764