---
# handlers file for php-ubuntu

- name: restart phpfpm
  service: name="php{{ php_v }}-fpm" state=restarted
  ignore_errors: yes

- name: restart apache
  service: name=apache2 state=restarted
  ignore_errors: yes