---
# tasks file for php-ubuntu

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo="{{ php5_ppa }}"

- name: ensure PHP installed
  apt: pkg={{ item }} state=latest
  with_items: php5_packages

- name: make sure /etc/php5/apache2/ directory exists
  shell: creates=/etc/php5/apache2/ mkdir -p /etc/php5/apache2/

- name: configure Apache PHP settings
  template: src={{ php5_apache2_template_src }} dest=/etc/php5/apache2/php.ini

- name: configure PHP-FPM settings
  template: src={{ php5_fpm_template_src }} dest=/etc/php5/fpm/php.ini