---
# defaults file for prepare-deploy-pack

prepare_hostname: sample.local # "{{ hostname }}"
prepare_project_name: yii2-advanced-master # Folder name without /var/www/
prepare_compress: true # Compress JS & CSS files
prepare_tmp_project_dir: /tmp/sample.local
prepare_git_repo: git@github.com:denisphp/yii2-advanced-master.git
prepare_branch: dev
prepare_compress_files: [
    { dir: 'frontend/web/js/', type: 'js'},
    { dir: 'frontend/web/css/', type: 'css'}
  ]
prepare_install_composer: false
prepare_remove_files: [
    'nbproject',
    'build',
    'provision',
    'ansible',
    '.DS_Store',
    '.gitignore',
    '.git',
    '.idea',
    'yuicompressor.jar',
    'README.md',
    'Vagrantfile'
  ]