---
# defaults file for prepare-deploy-pack
prepare_repository_path: "/home/gitlab-runner/project" # that variable needs only for local deploy
prepare_delegate_to: "127.0.0.1"
prepare_hostname: projectHostName # "{{ hostname }}"
prepare_project_name: projectName # Folder name without /var/www/
prepare_compress: true # Compress JS & CSS files
prepare_tmp_project_dir: /tmp/projectName
prepare_git_repo: git@gitlab.mobidev.biz:web/projectName.git
prepare_branch: dev
prepare_compress_files: [
    { dir: 'frontend/web/js/', type: 'js'},
    { dir: 'frontend/web/css/', type: 'css'}
  ]
prepare_install_composer: false
prepare_remove_files: [
    'nbproject',
    'build',
    'provision',
    'ansible',
    '.DS_Store',
    '.gitignore',
    '.git',
    '.idea',
    'yuicompressor.jar',
    'README.md',
    'Vagrantfile',
    'environments'
  ]