- hosts: dev
  sudo: true
  gather_facts: true
  vars_files:
    - "vars/dev.yml"
  roles:
    - initial
    - nginx
    - php-ubuntu
    - mariadb-10-1
    - phpmyadmin
    - composer
    - redis
    - phpredis
    - prepare-deploy-pack
    - deploy
    - after-update